services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: book-catalog-app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:1.25
    container_name: book-catalog-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: book-catalog-db
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
